# See https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
[profile.default]
src = 'src'
# for development
out = 'out'
libs = ['lib']
# for deploy
optimizer = true
optimizer-runs = 200
extra-output-files = [
  'metadata',
  'ir',
  'irOptimized',
  'ewasm',
  'evm.assembly',
]

[profile.default.optimizer_details]
constantOptimizer = true
yul = true
